### ISSUE TITLE
Cannot specify custom delimiter

### ISSUE THREAD

**Issue by neivv** [daramos/simple_csv#2]
It appears that the intented way to specify delimiter other than comma is to use SimpleCsvReader::with_options, but the option struct cannot be constructed as the fields are not public.

Additionally, README.md tells to use SimpleCsvReader::with_delimiter which does not exist.

**Comment by daramos** [comment]
Absolutely right. I appreciate you letting me know. I've neglected updating the Readme as you can see :)
